Exception subclass: #Error	instanceVariableNames: ''	classVariableNames: ''	poolDictionaries: ''	category: 'Exceptions-Kernel'!!Error methodsFor: 'exceptionDescription' stamp: 'ajh 9/4/2002 19:24'!defaultAction	"No one has handled this error, but now give them a chance to decide how to debug it.  If none handle this either then open debugger (see UnhandedError-defaultAction)"	UnhandledError signalForException: self! !!Error methodsFor: 'private' stamp: 'ajh 2/1/2003 00:54'!isResumable	"Determine whether an exception is resumable."	^ false! !